name: 'Random'
on:
  schedule:
    - cron: '0 19 * * *'
  push:
    branches:
    - 'random-*'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        percentage:
          - 75
        nixpkgs_channel:
        - nixos-20.09-small
    steps:
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:${{ matrix.nixpkgs_channel }}

    - name: Set up binary cache
      run: nix-env -iA cachix -f https://cachix.org/api/v1/install && cachix use emacs-ci

    # Install and configure elinter
    - name: Install elinter
      run: nix-env -if https://github.com/akirak/elinter/archive/v4.tar.gz
    - name: Configure elinter
      run: |
        # Set the linters and the Emacs version used for linting
        echo "ELINTER_LINTERS=checkdoc check-declare package-lint melpazoid" >> $GITHUB_ENV
        echo "EMACS_VERSION=27.1" >> $GITHUB_ENV

    - uses: actions/checkout@v2.4.0

    - name: Pick a random package
      run: ./random
      env:
        MELPA_TOP_PERCENTAGE_BOUND: ${{ matrix.percentage }}

    - name: Run lint on the package
      run: elinter -r ${RECIPE_FILE}
