name: 'Demo'
on:
  pull_request:
  push:
    paths-ignore:
      - '*.org'
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    # Install Nix
    - uses: cachix/install-nix-action@v10
    - name: Set up binary cache
      run: nix-env -iA cachix -f https://cachix.org/api/v1/install && cachix use emacs-ci

    # Install and configure elinter
    - name: Install elinter
      run: nix-env -if https://github.com/akirak/elinter/archive/v4.tar.gz -A main
    - name: Configure elinter
      run: |
        echo "::set-env name=ELINTER_LINTERS::checkdoc check-declare package-lint melpazoid"
        echo "::set-env NAME=EMACS_VERSION::27.1"

    # Demo

    - name: Check out lsp-dart
      uses: actions/checkout@v2
      with:
        repository: akirak/lsp-dart
        ref: elinter
        path: lsp-dart
    - run: elinter --ert-runner
      working-directory: ./lsp-dart
      env:
        ELINTER_ALLOW_WARNINGS: melpazoid

    - name: Check out reformatter.el
      uses: actions/checkout@v2
      with:
        repository: akirak/reformatter.el
        ref: elinter
        path: reformatter.el
    - run: elinter --ert --from-nixpkgs shfmt -- reformatter-tests.el
      working-directory: ./reformatter.el

    - name: Check out dhall-mode
      uses: actions/checkout@v2
      with:
        repository: akirak/dhall-mode
        ref: elinter
        path: dhall-mode
    - run: elinter
      working-directory: ./dhall-mode
